### ISSUE TITLE
Logo-brand-name too small and not enough contrast for Anne Barge

### ISSUE THREAD

**Issue by Download** [Download/bridalapp-static#10]
Compare

![image](https://cloud.githubusercontent.com/assets/153391/14242882/94c5bdf4-fa52-11e5-93eb-b33c2fbcb4ea.png)

to

![image](https://cloud.githubusercontent.com/assets/153391/14242898/a783253a-fa52-11e5-94f5-12bcb058ad1c.png)

**brandId**: `q4`

**Comment by Download** [comment]
Get rid of the symbol on the left and give all available space to the lettering

**Comment by Caelis22** [comment]
Gefixt
