### ISSUE TITLE
Django projectje backend

### ISSUE THREAD

**Issue by rmmr** [Download/bridalapp-static#16]
Ik help je graag !

**Comment by Download** [comment]
@adaptivdesign He he eindelijk tijd om met Django te gaan prutsen.

Ik heb een repo aangemaakt met een OpenShift Python/Django project:
https://github.com/Download/bridalapp-api/invitations

Het resultaat na deployen op OpenShift kun je hier zien:
http://bridalapp-api-bridalapp.44fs.preview.openshiftapps.com/

De repo staat nu nog even open maar ga ik private maken zodra er iets meer gewichtige zaken in komen. Ik zal jou toevoegen als collaborator.

Tot nu toe ziet het er allemaal goed uit moet ik zeggen. Mooi spul. Punt is dat ik echt honderden web frameworks / CMS en dergelijke langs heb zien komen over de jaren dus om me dan te gaan verdiepen in één die geschreven is in een taal die ik ook nog niet beheers, dat doe ik niet zo snel, Maar jouw enthousiasme voor Django straalde er gewoon vanaf dus dat was voor mij de aansporing. Bedankt daarvoor! Ik zie ook wel waarom je enthousiast bent. Cleane code, strakke architectuur, met zaken als DB migrations helemaal in de core verwerkt. Is echt goed over nagedacht. Ik heb wel nog een flinke learning curve om overheen te gaan maar ik kan je vertellen dat ik er nu toch wel heel serieus over na aan het denken ben om inderdaad zoals jij suggereerde Django te gebruiken als backend.

**Comment by Download** [comment]
@adaptivdesign 
Nou het prutsen is nu seriezere vormen aan het aannemen. Ik heb een nieuw skeleton projectje dat ook echt naar OpenShift gedeployed kan worden. Ik zal je er voor uitnodigen. 
https://github.com/Download/ba
