### ISSUE TITLE
Logo-brand-name too small, wrong format, colored for Crystalline

### ISSUE THREAD

**Issue by Download** [Download/bridalapp-static#8]
Compare

![image](https://cloud.githubusercontent.com/assets/153391/14241742/640bf552-fa4d-11e5-9bea-f5eb0efd8b11.png)

to

![image](https://cloud.githubusercontent.com/assets/153391/14241747/6aa5b588-fa4d-11e5-92d6-527d1e894e2c.png)

**brandId**: `s0`

**Comment by Download** [comment]
Cut the 'flower' at the top and give all available space to the lettering

Also, convert the image to black & white (Afbeelding -> Modus -> Grijswaarden) and enhance contrast where needed (Kleuren -> Helderheid / Contrast) so the lettering becomes pitch black.

**Comment by Caelis22** [comment]
Ook gefixt
